package com.zq.shop.web.mappers;

import com.zq.shop.web.bean.DUser;
import org.apache.ibatis.annotations.Param;

public interface DUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_user
     *
     * @mbg.generated
     */
    int insert(DUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_user
     *
     * @mbg.generated
     */
    int insertSelective(DUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_user
     *
     * @mbg.generated
     */
    DUser selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DUser record);
    DUser findOneByPhone(@Param("phone")String phone);



    DUser findOnebyEmail(@Param("email")String email);



    int updateOnlineByUid(@Param("updatedOnline")Integer updatedOnline,@Param("uid")Integer uid);




}