package com.zq.shop.web.mappers;
import java.util.List;

import com.zq.shop.web.bean.RoomUser;
import org.apache.ibatis.annotations.Param;

public interface RoomUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_room_user
     *
     * @mbg.generated
     */
    int insert(RoomUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_room_user
     *
     * @mbg.generated
     */
    int insertSelective(RoomUser record);

    List<RoomUser> findByRoomId(@Param("roomId")Integer roomId);
    List<RoomUser> findByRoomIdAndStatus(@Param("roomId")Integer roomId,@Param("status")Integer status);
    List<RoomUser> findByUidAndStatus(@Param("uid")Integer uid,@Param("status")Integer status);


    RoomUser findOneByUidAndStatus(@Param("uid")Integer uid,@Param("status")Integer status);







    int updateStatusByUidAndRoomId(@Param("updatedStatus")Integer updatedStatus,@Param("uid")Integer uid,@Param("roomId")Integer roomId);




}