package com.zq.shop.web.bean;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table zq_game
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Game {
    /**
     * Database Column Remarks:
     *   本场游戏id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game.game_id
     *
     * @mbg.generated
     */
    private Integer gameId;

    /**
     * Database Column Remarks:
     *   房间号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game.room_id
     *
     * @mbg.generated
     */
    private Integer roomId;

    /**
     * Database Column Remarks:
     *   未发牌初始牌组
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game.cards
     *
     * @mbg.generated
     */
    private String cards;

    /**
     * Database Column Remarks:
     *   游戏初始倍率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game.times
     *
     * @mbg.generated
     */
    private Integer times;

    /**
     * Database Column Remarks:
     *   游戏当前倍率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game.current_times
     *
     * @mbg.generated
     */
    private Integer currentTimes;

    /**
     * Database Column Remarks:
     *   当前发牌用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game.current_send_user
     *
     * @mbg.generated
     */
    private Integer currentSendUser;

    /**
     * Database Column Remarks:
     *   当前发牌总次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game.current_send_time
     *
     * @mbg.generated
     */
    private Integer currentSendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game.game_id
     *
     * @return the value of zq_game.game_id
     *
     * @mbg.generated
     */
    public Integer getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game.game_id
     *
     * @param gameId the value for zq_game.game_id
     *
     * @mbg.generated
     */
    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game.room_id
     *
     * @return the value of zq_game.room_id
     *
     * @mbg.generated
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game.room_id
     *
     * @param roomId the value for zq_game.room_id
     *
     * @mbg.generated
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game.cards
     *
     * @return the value of zq_game.cards
     *
     * @mbg.generated
     */
    public String getCards() {
        return cards;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game.cards
     *
     * @param cards the value for zq_game.cards
     *
     * @mbg.generated
     */
    public void setCards(String cards) {
        this.cards = cards;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game.times
     *
     * @return the value of zq_game.times
     *
     * @mbg.generated
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game.times
     *
     * @param times the value for zq_game.times
     *
     * @mbg.generated
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game.current_times
     *
     * @return the value of zq_game.current_times
     *
     * @mbg.generated
     */
    public Integer getCurrentTimes() {
        return currentTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game.current_times
     *
     * @param currentTimes the value for zq_game.current_times
     *
     * @mbg.generated
     */
    public void setCurrentTimes(Integer currentTimes) {
        this.currentTimes = currentTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game.current_send_user
     *
     * @return the value of zq_game.current_send_user
     *
     * @mbg.generated
     */
    public Integer getCurrentSendUser() {
        return currentSendUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game.current_send_user
     *
     * @param currentSendUser the value for zq_game.current_send_user
     *
     * @mbg.generated
     */
    public void setCurrentSendUser(Integer currentSendUser) {
        this.currentSendUser = currentSendUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game.current_send_time
     *
     * @return the value of zq_game.current_send_time
     *
     * @mbg.generated
     */
    public Integer getCurrentSendTime() {
        return currentSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game.current_send_time
     *
     * @param currentSendTime the value for zq_game.current_send_time
     *
     * @mbg.generated
     */
    public void setCurrentSendTime(Integer currentSendTime) {
        this.currentSendTime = currentSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game.create_time
     *
     * @return the value of zq_game.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game.create_time
     *
     * @param createTime the value for zq_game.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game.update_time
     *
     * @return the value of zq_game.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game.update_time
     *
     * @param updateTime the value for zq_game.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}