package com.zq.shop.web.bean;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table zq_game_user_cards
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class GameUserCards {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game_user_cards.card_id
     *
     * @mbg.generated
     */
    private Integer cardId;

    /**
     * Database Column Remarks:
     *   本场游戏id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game_user_cards.game_id
     *
     * @mbg.generated
     */
    private Integer gameId;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game_user_cards.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * Database Column Remarks:
     *   发的牌内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game_user_cards.card_name
     *
     * @mbg.generated
     */
    private String cardName;

    /**
     * Database Column Remarks:
     *   1:单张 2：双张 3：3带1 4：3带2 5：4带2 6：4张 7：王炸
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game_user_cards.card_type
     *
     * @mbg.generated
     */
    private Integer cardType;

    /**
     * Database Column Remarks:
     *   全局第几次发牌
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game_user_cards.send_card_time
     *
     * @mbg.generated
     */
    private Integer sendCardTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game_user_cards.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game_user_cards.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game_user_cards.card_id
     *
     * @return the value of zq_game_user_cards.card_id
     *
     * @mbg.generated
     */
    public Integer getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game_user_cards.card_id
     *
     * @param cardId the value for zq_game_user_cards.card_id
     *
     * @mbg.generated
     */
    public void setCardId(Integer cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game_user_cards.game_id
     *
     * @return the value of zq_game_user_cards.game_id
     *
     * @mbg.generated
     */
    public Integer getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game_user_cards.game_id
     *
     * @param gameId the value for zq_game_user_cards.game_id
     *
     * @mbg.generated
     */
    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game_user_cards.uid
     *
     * @return the value of zq_game_user_cards.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game_user_cards.uid
     *
     * @param uid the value for zq_game_user_cards.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game_user_cards.card_name
     *
     * @return the value of zq_game_user_cards.card_name
     *
     * @mbg.generated
     */
    public String getCardName() {
        return cardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game_user_cards.card_name
     *
     * @param cardName the value for zq_game_user_cards.card_name
     *
     * @mbg.generated
     */
    public void setCardName(String cardName) {
        this.cardName = cardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game_user_cards.card_type
     *
     * @return the value of zq_game_user_cards.card_type
     *
     * @mbg.generated
     */
    public Integer getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game_user_cards.card_type
     *
     * @param cardType the value for zq_game_user_cards.card_type
     *
     * @mbg.generated
     */
    public void setCardType(Integer cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game_user_cards.send_card_time
     *
     * @return the value of zq_game_user_cards.send_card_time
     *
     * @mbg.generated
     */
    public Integer getSendCardTime() {
        return sendCardTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game_user_cards.send_card_time
     *
     * @param sendCardTime the value for zq_game_user_cards.send_card_time
     *
     * @mbg.generated
     */
    public void setSendCardTime(Integer sendCardTime) {
        this.sendCardTime = sendCardTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game_user_cards.create_time
     *
     * @return the value of zq_game_user_cards.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game_user_cards.create_time
     *
     * @param createTime the value for zq_game_user_cards.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game_user_cards.update_time
     *
     * @return the value of zq_game_user_cards.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game_user_cards.update_time
     *
     * @param updateTime the value for zq_game_user_cards.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}