package com.zq.shop.web.bean;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table zq_game_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class GameUser {
    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game_user.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game_user.game_id
     *
     * @mbg.generated
     */
    private Integer gameId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game_user.room_id
     *
     * @mbg.generated
     */
    private Integer roomId;

    /**
     * Database Column Remarks:
     *   1 2 3三个位置
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game_user.room_sort
     *
     * @mbg.generated
     */
    private Integer roomSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game_user.cards
     *
     * @mbg.generated
     */
    private String cards;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game_user.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game_user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_game_user.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game_user.uid
     *
     * @return the value of zq_game_user.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game_user.uid
     *
     * @param uid the value for zq_game_user.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game_user.game_id
     *
     * @return the value of zq_game_user.game_id
     *
     * @mbg.generated
     */
    public Integer getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game_user.game_id
     *
     * @param gameId the value for zq_game_user.game_id
     *
     * @mbg.generated
     */
    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game_user.room_id
     *
     * @return the value of zq_game_user.room_id
     *
     * @mbg.generated
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game_user.room_id
     *
     * @param roomId the value for zq_game_user.room_id
     *
     * @mbg.generated
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game_user.room_sort
     *
     * @return the value of zq_game_user.room_sort
     *
     * @mbg.generated
     */
    public Integer getRoomSort() {
        return roomSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game_user.room_sort
     *
     * @param roomSort the value for zq_game_user.room_sort
     *
     * @mbg.generated
     */
    public void setRoomSort(Integer roomSort) {
        this.roomSort = roomSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game_user.cards
     *
     * @return the value of zq_game_user.cards
     *
     * @mbg.generated
     */
    public String getCards() {
        return cards;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game_user.cards
     *
     * @param cards the value for zq_game_user.cards
     *
     * @mbg.generated
     */
    public void setCards(String cards) {
        this.cards = cards;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game_user.type
     *
     * @return the value of zq_game_user.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game_user.type
     *
     * @param type the value for zq_game_user.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game_user.create_time
     *
     * @return the value of zq_game_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game_user.create_time
     *
     * @param createTime the value for zq_game_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_game_user.update_time
     *
     * @return the value of zq_game_user.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_game_user.update_time
     *
     * @param updateTime the value for zq_game_user.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}