package com.zq.shop.web.bean;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table zq_room
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Room {
    /**
     * Database Column Remarks:
     *   房间号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_room.room_id
     *
     * @mbg.generated
     */
    private Integer roomId;

    /**
     * Database Column Remarks:
     *   1:10倍 2：100倍 3：1000倍
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_room.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     * Database Column Remarks:
     *   房间初始倍率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_room.times
     *
     * @mbg.generated
     */
    private Integer times;

    /**
     * Database Column Remarks:
     *   用户数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_room.user_num
     *
     * @mbg.generated
     */
    private Integer userNum;

    /**
     * Database Column Remarks:
     *   当前游戏id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_room.current_game_id
     *
     * @mbg.generated
     */
    private Integer currentGameId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_room.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_room.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_room.room_id
     *
     * @return the value of zq_room.room_id
     *
     * @mbg.generated
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_room.room_id
     *
     * @param roomId the value for zq_room.room_id
     *
     * @mbg.generated
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_room.type
     *
     * @return the value of zq_room.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_room.type
     *
     * @param type the value for zq_room.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_room.times
     *
     * @return the value of zq_room.times
     *
     * @mbg.generated
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_room.times
     *
     * @param times the value for zq_room.times
     *
     * @mbg.generated
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_room.user_num
     *
     * @return the value of zq_room.user_num
     *
     * @mbg.generated
     */
    public Integer getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_room.user_num
     *
     * @param userNum the value for zq_room.user_num
     *
     * @mbg.generated
     */
    public void setUserNum(Integer userNum) {
        this.userNum = userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_room.current_game_id
     *
     * @return the value of zq_room.current_game_id
     *
     * @mbg.generated
     */
    public Integer getCurrentGameId() {
        return currentGameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_room.current_game_id
     *
     * @param currentGameId the value for zq_room.current_game_id
     *
     * @mbg.generated
     */
    public void setCurrentGameId(Integer currentGameId) {
        this.currentGameId = currentGameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_room.update_time
     *
     * @return the value of zq_room.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_room.update_time
     *
     * @param updateTime the value for zq_room.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_room.create_time
     *
     * @return the value of zq_room.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_room.create_time
     *
     * @param createTime the value for zq_room.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}