
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
#  context-path: "/"
spring:
  profiles: prod
  http:
    multipart:
      max-file-size: 10mb
      max-request-size: 100mb
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ddz?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456_aA
    tomcat:
      max-active: 100
      min-idle: 10
      min-evictable-idle-time-millis: 1800000
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      validation-query: select 1
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456_aA
    pool:
      max-active: 8
      max-wait: -1
      min-idle: 0
      max-idle: 8
    timeout: 0
  session:
    store-type: none
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  jackson:
    default-property-inclusion: non_null
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: com.zq.shop
logging:
  file: /developer/logger.log
  level: debug
zq:
  security:
    oauth2-properties:
      clients[1]:
        clientId: defaultApplication
        clientSecret: defaultApplicationSecret
      tokenStore: jwt
    social-properties:
#      qq:
#        appId: wxd951035cc1889308
#        appSecret: 4524aa7c0a83fe5346696a73eae76ce6
      wexin:
        appId: wxd951035cc1889308
        appSecret: 4524aa7c0a83fe5346696a73eae76ce6
    validate-code-properties:
      sms:
        url: "/user/register,/user/*/password"
  socket-server:
    port: 6333
security:
  basic:
    enabled: true
    path: "/swagger-ui.html"
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


